# Generated by Django 4.1 on 2022-08-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_user_options_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='locations',
        ),
    ]
